version: '3.9'

# Profiles:
# - infra: Solo infraestructura (default)
# - app: Aplicación completa (infra + servicios)
#
# Uso:
#   docker-compose up -d                    # Solo infra
#   docker-compose --profile app up -d      # Stack completo

services:
  # ═══════════════════════════════════════════════════════════
  # INFRAESTRUCTURA (siempre activa)
  # ═══════════════════════════════════════════════════════════
  
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: carpeta_ciudadana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  # ═══════════════════════════════════════════════════════════
  # APLICACIÓN (profile: app)
  # ═══════════════════════════════════════════════════════════

  frontend:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-frontend:${TAG:-local}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_OPERATOR_ID=operator-demo
      - NEXT_PUBLIC_OPERATOR_NAME=Carpeta Demo

  gateway:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-gateway:${TAG:-local}
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CITIZEN_SERVICE_URL=http://citizen:8000
      - INGESTION_SERVICE_URL=http://ingestion:8000
      - METADATA_SERVICE_URL=http://metadata:8000
      - TRANSFER_SERVICE_URL=http://transfer:8000
      - MINTIC_CLIENT_URL=http://mintic-client:8000
    depends_on:
      - redis

  citizen:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-citizen:${TAG:-local}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - MINTIC_CLIENT_URL=http://mintic-client:8000
    depends_on:
      - postgres

  ingestion:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-ingestion:${TAG:-local}
    environment:
      - ENVIRONMENT=development
      - CLOUD_PROVIDER=azure
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=documents
    depends_on:
      - postgres

  metadata:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-metadata:${TAG:-local}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    depends_on:
      - postgres
      - opensearch

  transfer:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-transfer:${TAG:-local}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
    depends_on:
      - postgres

  mintic-client:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-mintic_client:${TAG:-local}
    environment:
      - ENVIRONMENT=development
      - MINTIC_BASE_URL=https://govcarpeta-apis-4905ff3c005b.herokuapp.com
      - MINTIC_OPERATOR_ID=operator-demo
      - MINTIC_OPERATOR_NAME=Carpeta Ciudadana Demo

volumes:
  postgres_data:
  opensearch_data:
  redis_data:

