version: '3.9'

# Profiles:
# - infra: Solo infraestructura (default)
# - app: Aplicación completa (infra + servicios)
#
# Uso:
#   docker-compose up -d                    # Solo infra
#   docker-compose --profile app up -d      # Stack completo

services:
  # ═══════════════════════════════════════════════════════════
  # INFRAESTRUCTURA (siempre activa)
  # ═══════════════════════════════════════════════════════════
  
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: carpeta_ciudadana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  # Redis removed - using Azure Cache for Redis only

  # Jaeger removed - using Azure Application Insights instead

  # ═══════════════════════════════════════════════════════════
  # APLICACIÓN (profile: app)
  # ═══════════════════════════════════════════════════════════

  frontend:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-frontend:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_OPERATOR_ID=operator-demo
      - NEXT_PUBLIC_OPERATOR_NAME=Carpeta Demo
      - NEXTAUTH_SECRET=your-secret-key-for-development-only-change-in-production
      - NEXTAUTH_URL=http://localhost:3000

  # Gateway removed - using Azure API Management instead

  citizen:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-citizen:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - MINTIC_CLIENT_URL=http://mintic-client:8000
    depends_on:
      - postgres

  ingestion:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-ingestion:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - CLOUD_PROVIDER=azure
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=documents
    depends_on:
      - postgres

  metadata:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-metadata:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
    depends_on:
      - postgres
      - opensearch

  transfer:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-transfer:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
    depends_on:
      - postgres

  mintic-client:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-mintic_client:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - MINTIC_BASE_URL=https://govcarpeta-apis-4905ff3c005b.herokuapp.com
      - MINTIC_OPERATOR_ID=operator-demo
      - MINTIC_OPERATOR_NAME=Carpeta Ciudadana Demo
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=6380
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_SSL=false

  signature:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-signature:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - MINTIC_HUB_URL=https://govcarpeta-apis-4905ff3c005b.herokuapp.com
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=6380
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_SSL=false
      - SERVICE_BUS_ENABLED=false
    depends_on:
      - postgres

  auth:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-auth:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=6380
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - postgres

  notification:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-notification:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - SERVICE_BUS_ENABLED=false
    depends_on:
      - postgres

  read-models:
    profiles: ["app"]
    image: ${DOCKER_USERNAME:-manuelquistial}/carpeta-read_models:${TAG:-latest}
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/carpeta_ciudadana
      - REDIS_HOST=${REDIS_HOST:-}
      - REDIS_PORT=6380
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - postgres

volumes:
  postgres_data:
  opensearch_data:
