version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: carpeta_ciudadana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  # localstack:
  #   image: localstack/localstack:latest
  #   environment:
  #     - SERVICES=s3,sqs,sns,cognito-idp
  #     - DEBUG=1
  #     - DATA_DIR=/tmp/localstack/data
  #   ports:
  #     - "4566:4566"
  #   volumes:
  #     - localstack_data:/tmp/localstack
  #     - /var/run/docker.sock:/var/run/docker.sock
  # Comentado: usando Azure real en lugar de LocalStack

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

volumes:
  postgres_data:
  opensearch_data:
  # localstack_data:  # Comentado: LocalStack deshabilitado
  redis_data:

