{{/*
Migration Job Template
This template creates migration jobs for each service that needs database migrations
*/}}
{{- define "carpeta-ciudadana.migration" -}}
{{- $service := .service -}}
{{- $context := .context -}}
{{- if $context.Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "carpeta-ciudadana.fullname" $context }}-migrate-{{ $service }}
  labels:
    {{- include "carpeta-ciudadana.labels" $context | nindent 4 }}
    app.kubernetes.io/component: migration
    app.kubernetes.io/service: {{ $service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "carpeta-ciudadana.selectorLabels" $context | nindent 8 }}
        app.kubernetes.io/component: migration
        app.kubernetes.io/service: {{ $service }}
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" $context }}
      restartPolicy: Never
      containers:
      - name: migration
        image: {{ printf "%s/%s:%s" $context.Values.global.imageRegistry (printf "carpeta-ciudadana-%s" $service) $context.Values.global.imageTag | default "latest" }}
        imagePullPolicy: {{ $context.Values.global.imagePullPolicy }}
        command: ["dotnet", "run", "--project", "/app/src/CarpetaCiudadana.{{ $service | title }}.Infrastructure/CarpetaCiudadana.{{ $service | title }}.Infrastructure.csproj", "--", "migrate"]
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ $context.Values.global.environment | quote }}
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DATABASE_URL
        - name: AzureStorage__ConnectionString
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: STORAGE_CONNECTION_STRING
        # ServiceBus - REMOVED
        - name: Redis__ConnectionString
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: REDIS_CONNECTION_STRING
        {{- if eq $service "citizen" }}
        # Azure AD B2C - REMOVED
        {{- end }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      {{- with $context.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $context.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
