apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-app-flags
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
data:
  # MinTIC Hub Configuration
  HUB_BASE_URL: "{{ .Values.mintic.hubUrl | default "https://govcarpeta-apis-4905ff3c005b.herokuapp.com" }}"
  ALLOW_INSECURE_OPERATOR_URLS: "{{ .Values.mintic.allowInsecureUrls | default "false" }}"
  RATE_LIMIT_TO_HUB: "{{ .Values.mintic.rateLimit | default "10" }}"
  
  # Azure Storage SAS Configuration
  SAS_TTL_MINUTES: "{{ .Values.azure.storage.sasTtlMinutes | default "15" }}"
  
  # Circuit Breaker Configuration
  CB_WINDOW: "{{ .Values.circuitBreaker.window | default "60s" }}"
  CB_THRESHOLD: "{{ .Values.circuitBreaker.threshold | default "5" }}"
  CB_COOLDOWN: "{{ .Values.circuitBreaker.cooldown | default "120s" }}"
  
  # Service URLs (internal)
  GATEWAY_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-gateway:8000"
  CITIZEN_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-citizen:8000"
  INGESTION_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-ingestion:8000"
  METADATA_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-metadata:8000"
  TRANSFER_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-transfer:8000"
  SIGNATURE_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-signature:8000"
  NOTIFICATION_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-notification:8000"
  READ_MODELS_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-read-models:8000"
  MINTIC_CLIENT_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-mintic-client:8000"
  
  # OpenSearch Configuration
  OPENSEARCH_HOST: "opensearch-cluster-master"
  OPENSEARCH_PORT: "9200"
  
  # Redis Configuration
  REDIS_PORT: "6379"
  
  # Application Configuration
  LOG_LEVEL: "{{ .Values.global.logLevel | default "INFO" }}"
  ENVIRONMENT: "{{ .Values.global.environment }}"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "{{ .Values.global.environment }}"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=carpeta-ciudadana,deployment.environment={{ .Values.global.environment }}"
  
  # Feature Flags
  ENABLE_TELEMETRY: "{{ .Values.observability.enabled | default "true" }}"
  USE_MANAGED_IDENTITY: "true"
  PREFER_USER_DELEGATION_SAS: "true"

