apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-cors-origins
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
data:
  {{- if eq .Values.global.environment "development" }}
  # Development: Allow all origins for testing
  CORS_ORIGINS: "*"
  CORS_ALLOW_CREDENTIALS: "false"  # Cannot be true when origin is *
  {{- else if eq .Values.global.environment "production" }}
  # Production: Only allow frontend domain
  CORS_ORIGINS: {{ .Values.cors.allowedOrigins | quote }}
  CORS_ALLOW_CREDENTIALS: "true"
  {{- else }}
  # Staging/Other: Configurable
  CORS_ORIGINS: {{ .Values.cors.allowedOrigins | default "*" | quote }}
  CORS_ALLOW_CREDENTIALS: {{ .Values.cors.allowCredentials | default "false" | quote }}
  {{- end }}
  CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
  CORS_ALLOW_HEADERS: "Content-Type,Authorization,X-Request-ID,X-Client-Version"
  CORS_EXPOSE_HEADERS: "X-Request-ID,X-RateLimit-Remaining,X-RateLimit-Reset"
  CORS_MAX_AGE: "3600"

