apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-app-config
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: application
data:
  # =============================================================================
  # APPLICATION CONFIGURATION
  # =============================================================================
  
  # MinTIC Hub Configuration
  HUB_BASE_URL: "{{ .Values.mintic.hubUrl | default "https://govcarpeta-apis-4905ff3c005b.herokuapp.com" }}"
  ALLOW_INSECURE_OPERATOR_URLS: "{{ .Values.mintic.allowInsecureUrls | default "false" }}"
  RATE_LIMIT_TO_HUB: "{{ .Values.mintic.rateLimit | default "10" }}"
  
  # Azure Storage SAS Configuration
  SAS_TTL_MINUTES: "{{ .Values.azure.storage.sasTtlMinutes | default "15" }}"
  
  # Circuit Breaker Configuration
  CB_WINDOW: "{{ .Values.circuitBreaker.window | default "60s" }}"
  CB_THRESHOLD: "{{ .Values.circuitBreaker.threshold | default "5" }}"
  CB_COOLDOWN: "{{ .Values.circuitBreaker.cooldown | default "120s" }}"
  
  # Service URLs (internal)
  AUTH_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-auth:8000"
  CITIZEN_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-citizen:8000"
  INGESTION_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-ingestion:8000"
  TRANSFER_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-transfer:8000"
  SIGNATURE_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-signature:8000"
  MINTIC_CLIENT_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-mintic-client:8000"
  
  # Frontend URLs (for service-to-service communication)
  FRONTEND_URL: "http://{{ include "carpeta-ciudadana.fullname" . }}-frontend:80"
  
  
  # Redis Configuration
  REDIS_PORT: "6379"
  
  # Application Configuration
  LOG_LEVEL: "{{ .Values.global.logLevel | default "INFO" }}"
  ENVIRONMENT: "{{ .Values.global.environment }}"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "{{ .Values.global.environment }}"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=carpeta-ciudadana,deployment.environment={{ .Values.global.environment }}"
  
  # Feature Flags
  ENABLE_TELEMETRY: "{{ .Values.observability.enabled | default "true" }}"
  USE_MANAGED_IDENTITY: "true"
  PREFER_USER_DELEGATION_SAS: "true"
  
  # =============================================================================
  # CORS CONFIGURATION
  # =============================================================================
  
  # CORS Configuration (restrictive)
  CORS_ORIGINS: {{ .Values.global.corsOrigins | quote }}
  CORS_ALLOW_CREDENTIALS: "true"
  
  # Allowed methods (restrictive)
  CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  
  # Allowed headers (restrictive)
  CORS_ALLOW_HEADERS: "Content-Type,Authorization,X-Request-ID,X-Trace-ID,X-Span-ID,Accept,Accept-Language,Content-Language"
  
  # Expose headers
  CORS_EXPOSE_HEADERS: "X-Request-ID,X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Reset"
  
  # Preflight cache (1 hour)
  CORS_MAX_AGE: "3600"
  
  # Security Headers Configuration
  SECURITY_HEADERS_ENABLED: "true"
  HSTS_ENABLED: {{ .Values.security.hstsEnabled | quote }}
  CSP_ENABLED: {{ .Values.security.cspEnabled | quote }}
  CSP_REPORT_URI: {{ .Values.security.cspReportUri | quote }}

