apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-cors-config
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
data:
  # CORS Configuration (restrictive)
  CORS_ORIGINS: {{ .Values.global.corsOrigins | quote }}
  CORS_ALLOW_CREDENTIALS: "true"
  
  # Allowed methods (restrictive)
  CORS_ALLOW_METHODS: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  
  # Allowed headers (restrictive)
  CORS_ALLOW_HEADERS: "Content-Type,Authorization,X-Request-ID,X-Trace-ID,X-Span-ID,Accept,Accept-Language,Content-Language"
  
  # Expose headers
  CORS_EXPOSE_HEADERS: "X-Request-ID,X-RateLimit-Limit,X-RateLimit-Remaining,X-RateLimit-Reset"
  
  # Preflight cache (1 hour)
  CORS_MAX_AGE: "3600"
  
  # Security Headers Configuration
  SECURITY_HEADERS_ENABLED: "true"
  HSTS_ENABLED: {{ .Values.global.security.hstsEnabled | quote }}
  CSP_ENABLED: {{ .Values.global.security.cspEnabled | quote }}
  CSP_REPORT_URI: {{ .Values.global.security.cspReportUri | quote }}
