{{- if .Values.metadata.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-metadata
  labels:
    app: metadata
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.metadata.replicaCount }}
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      containers:
      - name: metadata
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.metadata.image.repository }}:{{ .Values.metadata.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: DATABASE_URL
          value: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.auth.database }}"
        - name: OPENSEARCH_HOST
          value: {{ .Values.opensearch.host }}
        - name: OPENSEARCH_PORT
          value: "{{ .Values.opensearch.port }}"
        resources:
          {{- toYaml .Values.metadata.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-metadata
  labels:
    app: metadata
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metadata.service.type }}
  ports:
  - port: {{ .Values.metadata.service.port }}
    targetPort: 8000
    name: http
  selector:
    app: metadata
---
{{- if .Values.metadata.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-metadata
  labels:
    app: metadata
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-metadata
  minReplicas: {{ .Values.metadata.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.metadata.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.metadata.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

