{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      containers:
      - name: frontend
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        # Service URLs for frontend
        - name: NEXT_PUBLIC_AUTH_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/auth"
        - name: NEXT_PUBLIC_CITIZEN_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/users"
        - name: NEXT_PUBLIC_INGESTION_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/documents"
        - name: NEXT_PUBLIC_METADATA_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/metadata"
        - name: NEXT_PUBLIC_SIGNATURE_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/signature"
        - name: NEXT_PUBLIC_TRANSFER_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/transfers"
        - name: NEXT_PUBLIC_MINTIC_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/mintic"
        - name: NEXT_PUBLIC_READ_MODELS_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/dashboard"
        - name: NEXT_PUBLIC_NOTIFICATION_SERVICE_URL
          value: "{{ .Values.frontend.nextAuth.url }}/api/notifications"
        - name: NEXT_PUBLIC_OPERATOR_ID
          value: "{{ .Values.global.operatorId | default "operator-demo" }}"
        - name: NEXT_PUBLIC_OPERATOR_NAME
          value: "{{ .Values.global.operatorName | default "Carpeta Ciudadana Demo" }}"
        - name: NODE_ENV
          value: "production"
        # NextAuth Configuration - from Kubernetes secrets
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: NEXTAUTH_SECRET
              optional: true
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: nextauth-secret
              key: NEXTAUTH_URL
              optional: true
        # Azure AD Configuration - from Kubernetes secrets
        - name: AZURE_AD_B2C_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-b2c-secrets
              key: tenant_id
              optional: true
        - name: AZURE_AD_B2C_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-b2c-secrets
              key: client_id
              optional: true
        - name: AZURE_AD_B2C_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-b2c-secrets
              key: client_secret
              optional: true
        - name: AZURE_AD_B2C_PRIMARY_USER_FLOW
          value: "{{ .Values.azureB2C.userFlowName | default "B2C_1_signupsignin1" }}"
        envFrom:
        - configMapRef:
            name: {{ include "carpeta-ciudadana.fullname" . }}-app-flags
            optional: true
        - configMapRef:
            name: frontend-auth-config
            optional: true
        - secretRef:
            name: nextauth-secret
            optional: true
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
---
{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
  {{- if .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}
