{{- if .Values.auth.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-auth
  labels:
    app: auth
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      containers:
      - name: auth
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        # OIDC Configuration
        - name: OIDC_ISSUER_URL
          value: "{{ .Values.auth.oidcIssuerUrl | default "" }}"
        # JWT configuration - these values come from the ConfigMap
        # - name: JWT_ACCESS_TOKEN_EXPIRE (defined in ConfigMap)
        # - name: JWT_REFRESH_TOKEN_EXPIRE_DAYS (defined in ConfigMap)
        
        # Azure AD B2C - REMOVED
        
        # Redis (session storage from Azure Key Vault)
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: REDIS_HOST
              optional: true
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: REDIS_PORT
              optional: true
        - name: REDIS_SESSION_DB
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: REDIS_SESSION_DB
              optional: true
        
        # CORS
        - name: CORS_ALLOWED_ORIGINS
          value: "{{ .Values.global.corsOrigins | default "http://localhost:3000" }}"
        
        # Logging
        - name: LOG_LEVEL
          value: "{{ .Values.auth.logLevel | default "INFO" }}"
        - name: ENVIRONMENT
          value: "{{ .Values.global.environment | default "dev" }}"
        
        # Service Bus configuration
        - name: SERVICEBUS_ENABLED
          value: "{{ .Values.serviceBus.enabled | default false }}"
        {{- if .Values.serviceBus.enabled }}
        - name: SERVICEBUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: sb-conn
              key: SERVICEBUS_CONNECTION_STRING
              optional: true
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "carpeta-ciudadana.fullname" . }}-app-config
        - secretRef:
            name: database-credentials
        - secretRef:
            name: azure-secrets
            optional: true
        - secretRef:
            name: app-secrets
            optional: true
        - secretRef:
            name: jwt-secret
            optional: true
        resources:
          {{- toYaml .Values.auth.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-auth
  labels:
    app: auth
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
  - port: {{ .Values.auth.service.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: auth
---
{{- if .Values.auth.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-auth
  labels:
    app: auth
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-auth
  minReplicas: {{ .Values.auth.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.auth.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
