{{- include "carpeta-ciudadana.deployment" (dict "service" "notification" "context" .) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-notification
  labels:
    app: notification
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notification.service.type }}
  ports:
  - port: {{ .Values.notification.service.port }}
    targetPort: 8010
    protocol: TCP
    name: http
  selector:
    app: notification
---
{{- if .Values.notification.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-notification
  labels:
    app: notification
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-notification
  minReplicas: {{ .Values.notification.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.notification.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.notification.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
