{{- if .Values.gateway.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-gateway
  labels:
    app: gateway
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      containers:
      - name: gateway
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: {{ .Values.global.environment }}
        - name: RATE_LIMIT_PER_MINUTE
          value: "60"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: CITIZEN_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-citizen:8000"
        - name: INGESTION_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-ingestion:8000"
        - name: METADATA_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-metadata:8000"
        - name: SIGNATURE_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-signature:8000"
        - name: TRANSFER_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-transfer:8000"
        - name: SHARING_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-sharing:8000"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-notification:8000"
        - name: MINTIC_CLIENT_URL
          value: "http://{{ include "carpeta-ciudadana.fullname" . }}-mintic-client:8000"
        resources:
          {{- toYaml .Values.gateway.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-gateway
  labels:
    app: gateway
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: 8000
    name: http
  selector:
    app: gateway
---
{{- if .Values.gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-gateway
  labels:
    app: gateway
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-gateway
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

