# External Secret para Application Secrets (M2M Auth, JWT, NextAuth, API Keys)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: application
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
  # M2M Authentication
  - secretKey: M2M_SECRET_KEY
    remoteRef:
      key: m2m-auth
      property: secret-key
  - secretKey: M2M_MAX_TIMESTAMP_AGE
    remoteRef:
      key: m2m-auth
      property: max-timestamp-age
  - secretKey: M2M_NONCE_TTL
    remoteRef:
      key: m2m-auth
      property: nonce-ttl

---
# External Secret para JWT
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: jwt
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: jwt
      property: secret-key

---
# External Secret para NextAuth
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextauth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: nextauth
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: nextauth-secret
    creationPolicy: Owner
  data:
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: nextauth
      property: secret
  - secretKey: NEXTAUTH_URL
    remoteRef:
      key: nextauth
      property: url

---
# External Secret para API Keys
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: api
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: api-keys
    creationPolicy: Owner
  data:
  - secretKey: OPERATOR_API_KEY
    remoteRef:
      key: api-keys
      property: operator-api-key
