# External Secret para NextAuth Configuration
# DISABLED: Secret 'nextauth-secrets' does not exist in Azure Key Vault
# {{/*
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: nextauth-secret
#   namespace: {{ .Release.Namespace }}
#   labels:
#     {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
#     component: nextauth
# spec:
#   refreshInterval: "5m"
#   secretStoreRef:
#     name: azure-keyvault-store
#     kind: SecretStore
#   target:
#     name: nextauth-secret
#     creationPolicy: Owner
#   data:
#   - secretKey: NEXTAUTH_SECRET
#     remoteRef:
#       key: nextauth-secrets
#       property: secret
#   - secretKey: NEXTAUTH_URL
#     remoteRef:
#       key: nextauth-secrets
#       property: url
# */}}
