apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: servicebus-secrets-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: servicebus
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: servicebus-secrets-metadata
    creationPolicy: Owner
  data:
  - secretKey: SERVICEBUS_CONNECTION_STRING
    remoteRef:
      key: servicebus-document-events
      property: connection-string








