# External Secrets Operator - SecretStore para Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: external-secrets
  annotations:
    # Anotación para forzar actualización
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
spec:
  provider:
    azurekv:
      vaultUrl: {{ .Values.keyvault.vaultUrl | quote }}
      authType: "ManagedIdentity"
      environmentType: "PublicCloud"
      identity:
        clientId: {{ .Values.keyvault.clientId | quote }}
