{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.certManager.enabled }}
    # cert-manager annotations
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManager.clusterIssuer | quote }}
    {{- if .Values.ingress.tls.certManager.acmeChallenge }}
    cert-manager.io/acme-challenge-type: {{ .Values.ingress.tls.certManager.acmeChallenge }}
    {{- end }}
    {{- end }}
    # Security Headers
    nginx.ingress.kubernetes.io/custom-http-errors: "404,500,502,503,504"
    {{- if .Values.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    {{- end }}
    # Basic security settings
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    # Body size limits (gateway handles metadata, not file uploads)
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "1m"
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rateLimitRps | default "100" }}"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    # Timeouts
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled (not (eq .Values.ingress.tls.secretName "")) }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .host }}
  - hosts:
    - {{ .host }}
    secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  {{- if .host }}
  - host: {{ .host }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      # Frontend routes (Next.js app)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-frontend
            port:
              number: 80
      # API routes - Auth Service
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-auth
            port:
              number: 8000
      # API routes - Citizen Service
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-citizen
            port:
              number: 8000
      # API routes - Document Services
      - path: /api/documents
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-ingestion
            port:
              number: 8000
      - path: /api/metadata
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-metadata
            port:
              number: 8000
      - path: /api/signature
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-signature
            port:
              number: 8000
      # API routes - Transfer Service
      - path: /api/transfers
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-transfer
            port:
              number: 8000
      # API routes - MinTIC Service
      - path: /api/mintic
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-mintic-client
            port:
              number: 8000
      # API routes - Read Models Service
      - path: /api/dashboard
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-read-models
            port:
              number: 8007
      # Health check routes
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ include "carpeta-ciudadana.fullname" $ }}-auth
            port:
              number: 8000
  {{- end }}
{{- end }}

