{{- if .Values.metadata.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-migrate-metadata-{{ .Release.Revision }}
  labels:
    app: migrate-metadata
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      name: migrate-metadata
      labels:
        app: migrate-metadata
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      containers:
      - name: migrate
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.metadata.image.repository }}:{{ .Values.metadata.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "🔄 Running metadata database migrations..."
          
          # Check if alembic is available
          if command -v alembic >/dev/null 2>&1; then
            echo "Using Alembic for migrations"
            cd /app
            alembic upgrade head
          elif [ -f "/app/migrations/init.sql" ]; then
            echo "Using SQL scripts for migrations"
            psql $POSTGRES_URI -f /app/migrations/init.sql
          else
            echo "⚠️  No migration tool found, skipping..."
          fi
          
          echo "✅ Metadata migrations completed successfully"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "carpeta-ciudadana.fullname" . }}-database
              key: DATABASE_URL
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              name: {{ include "carpeta-ciudadana.fullname" . }}-database
              key: POSTGRES_URI
        envFrom:
        - configMapRef:
            name: {{ include "carpeta-ciudadana.fullname" . }}-app-flags
{{- end }}

