{{- if .Values.sharing.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-migrate-sharing-{{ .Release.Revision }}
  labels:
    app: sharing
    component: migration
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: sharing
        component: migration
    spec:
      serviceAccountName: {{ include "carpeta-ciudadana.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: migrate
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.sharing.image.repository }}:{{ .Values.sharing.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["sh", "-c"]
        args:
          - |
            echo "Running sharing database migrations..."
            cd /app
            
            # Check if alembic is configured
            if [ -f "alembic.ini" ]; then
              alembic upgrade head
              echo "✅ Sharing migrations completed"
            else
              echo "⚠️  No alembic configuration found for sharing service"
              echo "Skipping migrations"
            fi
        envFrom:
        - configMapRef:
            name: {{ include "carpeta-ciudadana.fullname" . }}-app-flags
        - secretRef:
            name: db-secrets
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
{{- end }}

