{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: gateway
  
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules - Who can call gateway
  ingress:
  # Allow from Ingress Controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  
  # Allow from frontend (same namespace)
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8000
  
  # Allow from observability (Prometheus scraping)
  - from:
    - namespaceSelector:
        matchLabels:
          name: observability
    ports:
    - protocol: TCP
      port: 8000
  
  # Egress rules - What gateway can call
  egress:
  # DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  
  # Internal services (same namespace)
  - to:
    - podSelector:
        matchLabels:
          app: citizen
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: ingestion
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: metadata
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: transfer
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: signature
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: sharing
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: read-models
    ports:
    - protocol: TCP
      port: 8007
  
  - to:
    - podSelector:
        matchLabels:
          app: notification
    ports:
    - protocol: TCP
      port: 8010
  
  - to:
    - podSelector:
        matchLabels:
          app: mintic-client
    ports:
    - protocol: TCP
      port: 8000
  
  # Redis (rate limiter)
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  
  # External APIs (MinTIC Hub)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  
  # HTTPS for external services
  - ports:
    - protocol: TCP
      port: 443
{{- end }}

