{{- if .Values.networkPolicies.enabled -}}
{{- if .Values.transferWorker.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-transfer-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: transfer-worker
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: transfer-worker
  
  policyTypes:
  - Ingress
  - Egress
  
  ingress:
  # Allow only from observability (no HTTP traffic expected)
  - from:
    - namespaceSelector:
        matchLabels:
          name: observability
    ports:
    - protocol: TCP
      port: 8012
  
  egress:
  # DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  
  # PostgreSQL
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5432
  
  # Azure Service Bus (consumer)
  - ports:
    - protocol: TCP
      port: 443
  
  # Redis
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  
  # Can call other internal services for orchestration
  - to:
    - podSelector:
        matchLabels:
          app: citizen
    ports:
    - protocol: TCP
      port: 8000
  
  - to:
    - podSelector:
        matchLabels:
          app: notification
    ports:
    - protocol: TCP
      port: 8010
{{- end }}
{{- end }}

