{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: frontend
  
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules
  ingress:
  # Allow from Ingress Controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  
  # Allow from observability (Prometheus)
  - from:
    - namespaceSelector:
        matchLabels:
          name: observability
    ports:
    - protocol: TCP
      port: 3000
  
  # Allow from anywhere (public frontend)
  - ports:
    - protocol: TCP
      port: 3000
  
  # Egress rules
  egress:
  # DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  
  # Gateway (API calls)
  - to:
    - podSelector:
        matchLabels:
          app: gateway
    ports:
    - protocol: TCP
      port: 8000
  
  # Azure AD B2C (authentication)
  - ports:
    - protocol: TCP
      port: 443
  
  # External CDNs and APIs
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}

