{{- if .Values.podDisruptionBudget.enabled -}}


# PodDisruptionBudget for Citizen
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-citizen
  namespace: {{ .Release.Namespace }}
  labels:
    app: citizen
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: citizen

# PodDisruptionBudget for Ingestion
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    app: ingestion
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: ingestion


# PodDisruptionBudget for Transfer (CRITICAL - Saga orchestrator)
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-transfer
  namespace: {{ .Release.Namespace }}
  labels:
    app: transfer
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: transfer

# PodDisruptionBudget for Signature (CRITICAL - WORM activation)
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-signature
  namespace: {{ .Release.Namespace }}
  labels:
    app: signature
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: signature

# PodDisruptionBudget for MinTIC Client
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-mintic-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: mintic-client
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: mintic-client

# PodDisruptionBudget for Sharing



# PodDisruptionBudget for Transfer Worker (KEDA-aware)
{{- if .Values.transferWorker.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-transfer-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: transfer-worker
spec:
  # For KEDA scaled workloads, allow scaling to zero
  minAvailable: 0
  selector:
    matchLabels:
      app: transfer-worker
{{- end }}

# PodDisruptionBudget for Frontend
{{- if .Values.frontend.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.defaultMinAvailable | default 1 }}
  selector:
    matchLabels:
      app: frontend
{{- end }}

{{- end }}

