{{- if .Values.transferWorker.enabled -}}
{{- if .Values.transferWorker.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-transfer-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: transfer-worker
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "carpeta-ciudadana.fullname" . }}-transfer-worker
  
  # Polling interval
  pollingInterval: {{ .Values.transferWorker.keda.pollingInterval }}
  
  # Cooldown period after last trigger reported active
  cooldownPeriod: {{ .Values.transferWorker.keda.cooldownPeriod }}
  
  # Minimum number of replicas (0 = scale to zero)
  minReplicaCount: {{ .Values.transferWorker.keda.minReplicas }}
  
  # Maximum number of replicas
  maxReplicaCount: {{ .Values.transferWorker.keda.maxReplicas }}
  
  # Fallback configuration
  fallback:
    failureThreshold: 3
    replicas: {{ .Values.transferWorker.keda.fallbackReplicas }}
  
  # Advanced scaling behavior
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.transferWorker.keda.scaleDownStabilization }}
          policies:
          - type: Percent
            value: 50
            periodSeconds: 60
          - type: Pods
            value: 2
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 4
            periodSeconds: 15
          selectPolicy: Max
  
  triggers:
  # Azure Service Bus Queue Length Trigger
  - type: azure-servicebus
    metadata:
      # Queue name
      queueName: {{ .Values.transferWorker.keda.queueName }}
      
      # Namespace (format: namespace-name without .servicebus.windows.net)
      namespace: {{ .Values.servicebus.namespace }}
      
      # Target queue length per replica
      messageCount: "{{ .Values.transferWorker.keda.targetQueueLength }}"
      
      # Activation threshold (minimum messages to activate scaling from 0)
      activationMessageCount: "{{ .Values.transferWorker.keda.activationThreshold }}"
    
    # Authentication using TriggerAuthentication
    authenticationRef:
      name: {{ .Values.transferWorker.keda.triggerAuthName }}
  
  {{- if .Values.transferWorker.keda.cpuTrigger.enabled }}
  # CPU Trigger (optional, for additional scaling criteria)
  - type: cpu
    metricType: Utilization
    metadata:
      value: "{{ .Values.transferWorker.keda.cpuTrigger.targetUtilization }}"
  {{- end }}
  
  {{- if .Values.transferWorker.keda.memoryTrigger.enabled }}
  # Memory Trigger (optional)
  - type: memory
    metricType: Utilization
    metadata:
      value: "{{ .Values.transferWorker.keda.memoryTrigger.targetUtilization }}"
  {{- end }}

---
# TriggerAuthentication for Azure Service Bus
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Values.transferWorker.keda.triggerAuthName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: transfer-worker
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  {{- if .Values.global.useWorkloadIdentity }}
  # Use Azure Workload Identity
  podIdentity:
    provider: azure-workload
  {{- else }}
  # Use connection string from secret
  secretTargetRef:
  - parameter: connection
    name: sb-conn
    key: SERVICEBUS_CONNECTION_STRING
  {{- end }}
{{- end }}
{{- end }}

