apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: redis
type: Opaque
stringData:
  # Redis Configuration
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | default "6379" | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  REDIS_SSL: {{ .Values.redis.ssl | default "false" | quote }}
  REDIS_SESSION_DB: "1"
