{{- if or .Values.global.m2mAuth.enabled (and .Values.frontend.enabled .Values.frontend.nextAuth) }}
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: application
type: Opaque
stringData:
  {{- if .Values.global.m2mAuth.enabled }}
  # M2M Authentication Configuration
  M2M_SECRET_KEY: {{ .Values.global.m2mAuth.secretKey | default "change-me-in-production" | quote }}
  M2M_MAX_TIMESTAMP_AGE: {{ .Values.global.m2mAuth.maxTimestampAge | default "300" | quote }}
  M2M_NONCE_TTL: {{ .Values.global.m2mAuth.nonceTtl | default "600" | quote }}
  {{- end }}
  
  {{- if and .Values.frontend.enabled .Values.frontend.nextAuth }}
  # NextAuth Configuration
  NEXTAUTH_SECRET: {{ .Values.frontend.nextAuth.secret | quote }}
  NEXTAUTH_URL: {{ .Values.frontend.nextAuth.url | quote }}
  {{- end }}
{{- end }}
