{{- if .Values.global.keyVault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: carpeta-ciudadana
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  provider: azure
  
  parameters:
    # Use Workload Identity
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.keyVault.clientId | quote }}
    
    # Key Vault details
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    
    # Secrets to fetch
    objects: |
      array:
        # PostgreSQL secrets
        - |
          objectName: postgres-host
          objectType: secret
          objectAlias: POSTGRES_HOST
        - |
          objectName: postgres-username
          objectType: secret
          objectAlias: POSTGRES_USER
        - |
          objectName: postgres-password
          objectType: secret
          objectAlias: POSTGRES_PASSWORD
        - |
          objectName: postgres-database
          objectType: secret
          objectAlias: POSTGRES_DB
        
        # Service Bus secrets
        - |
          objectName: servicebus-connection-string
          objectType: secret
          objectAlias: SERVICEBUS_CONNECTION_STRING
        
        # M2M Authentication
        - |
          objectName: m2m-secret-key
          objectType: secret
          objectAlias: M2M_SECRET_KEY
        
        # Azure Storage
        - |
          objectName: storage-account-name
          objectType: secret
          objectAlias: AZURE_STORAGE_ACCOUNT_NAME
        
        # Redis (optional)
        - |
          objectName: redis-password
          objectType: secret
          objectAlias: REDIS_PASSWORD
        
        # OpenSearch
        - |
          objectName: opensearch-username
          objectType: secret
          objectAlias: OS_USERNAME
        - |
          objectName: opensearch-password
          objectType: secret
          objectAlias: OS_PASSWORD
  
  # Sync to Kubernetes secrets (optional, for backward compatibility)
  {{- if .Values.global.keyVault.syncToK8sSecrets }}
  secretObjects:
  - secretName: db-secrets-kv
    type: Opaque
    data:
    - objectName: POSTGRES_HOST
      key: POSTGRES_HOST
    - objectName: POSTGRES_USER
      key: POSTGRES_USER
    - objectName: POSTGRES_PASSWORD
      key: POSTGRES_PASSWORD
    - objectName: POSTGRES_DB
      key: POSTGRES_DB
  
  - secretName: sb-secrets-kv
    type: Opaque
    data:
    - objectName: SERVICEBUS_CONNECTION_STRING
      key: SERVICEBUS_CONNECTION_STRING
  
  - secretName: m2m-auth-kv
    type: Opaque
    data:
    - objectName: M2M_SECRET_KEY
      key: M2M_SECRET_KEY
  
  - secretName: azure-storage-kv
    type: Opaque
    data:
    - objectName: AZURE_STORAGE_ACCOUNT_NAME
      key: AZURE_STORAGE_ACCOUNT_NAME
  
  - secretName: opensearch-auth-kv
    type: Opaque
    data:
    - objectName: OS_USERNAME
      key: OS_USERNAME
    - objectName: OS_PASSWORD
      key: OS_PASSWORD
  {{- end }}

---
# SecretProviderClass for Azure AD B2C (if configured)
{{- if .Values.global.azureB2C.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-b2c-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: carpeta-ciudadana
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  provider: azure
  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.global.keyVault.name | quote }}
    tenantId: {{ .Values.global.keyVault.tenantId | quote }}
    
    objects: |
      array:
        - |
          objectName: azure-b2c-tenant-id
          objectType: secret
          objectAlias: AZURE_AD_B2C_TENANT_ID
        - |
          objectName: azure-b2c-client-id
          objectType: secret
          objectAlias: AZURE_AD_B2C_CLIENT_ID
        - |
          objectName: azure-b2c-client-secret
          objectType: secret
          objectAlias: AZURE_AD_B2C_CLIENT_SECRET
  
  {{- if .Values.global.keyVault.syncToK8sSecrets }}
  secretObjects:
  - secretName: azure-b2c-kv
    type: Opaque
    data:
    - objectName: AZURE_AD_B2C_TENANT_ID
      key: tenant_id
    - objectName: AZURE_AD_B2C_CLIENT_ID
      key: client_id
    - objectName: AZURE_AD_B2C_CLIENT_SECRET
      key: client_secret
  {{- end }}
{{- end }}
{{- end }}

