apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: database
type: Opaque
stringData:
  # Database Configuration (alias for database-secrets)
  DATABASE_URL: {{ .Values.database.connectionString | quote }}
  POSTGRES_URI: {{ .Values.database.connectionString | quote }}
  
  # Azure PostgreSQL specific variables
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | default 5432 | quote }}
  DB_NAME: {{ .Values.database.database | quote }}
  DB_USER: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  DB_SSLMODE: "require"
