{{- if false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-database
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://psqladmin:CarpetaCiudadana2024!Secure@dev-psql-server.postgres.database.azure.com:5432/carpeta_ciudadana"
  POSTGRES_URI: "postgresql://psqladmin:CarpetaCiudadana2024!Secure@dev-psql-server.postgres.database.azure.com:5432/carpeta_ciudadana"
{{- end }}

