{{- if .Values.global.m2mAuth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.m2mAuth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: carpeta-ciudadana
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
type: Opaque
stringData:
  # M2M Authentication Secret Key (shared across all services)
  # Generate with: openssl rand -hex 32
  M2M_SECRET_KEY: {{ .Values.global.m2mAuth.secretKey | default "change-me-in-production" | quote }}
  
  # M2M Configuration
  M2M_MAX_TIMESTAMP_AGE: {{ .Values.global.m2mAuth.maxTimestampAge | default "300" | quote }}
  M2M_NONCE_TTL: {{ .Values.global.m2mAuth.nonceTtl | default "600" | quote }}
{{- end }}

