{{- if or .Values.azureB2C.enabled .Values.serviceBus.enabled .Values.azure.storage.accountName }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: azure
type: Opaque
stringData:
  {{- if .Values.azureB2C.enabled }}
  # Azure AD B2C Configuration
  AZURE_AD_B2C_TENANT_NAME: {{ .Values.azureB2C.tenantName | quote }}
  AZURE_AD_B2C_TENANT_ID: {{ .Values.azureB2C.tenantId | quote }}
  AZURE_AD_B2C_CLIENT_ID: {{ .Values.azureB2C.clientId | quote }}
  AZURE_AD_B2C_CLIENT_SECRET: {{ .Values.azureB2C.clientSecret | quote }}
  {{- end }}
  
  {{- if .Values.azure.storage.accountName }}
  # Azure Storage Configuration
  AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.azure.storage.accountName | quote }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.azure.storage.accountKey | quote }}
  AZURE_STORAGE_CONTAINER_NAME: {{ .Values.azure.storage.containerName | default "documents" | quote }}
  {{- end }}
  
  {{- if .Values.serviceBus.enabled }}
  # Azure Service Bus Configuration
  SERVICEBUS_CONNECTION_STRING: {{ .Values.serviceBus.connectionString | quote }}
  {{- end }}
{{- end }}
