{{- if and .Values.frontend.enabled .Values.frontend.nextAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: nextauth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    component: nextauth
type: Opaque
stringData:
  # NextAuth Configuration
  NEXTAUTH_SECRET: {{ .Values.frontend.nextAuth.secret | quote }}
  NEXTAUTH_URL: {{ .Values.frontend.nextAuth.url | quote }}
  
  # Azure AD B2C for NextAuth
  AZURE_AD_B2C_TENANT_ID: {{ .Values.azureB2C.tenantId | quote }}
  AZURE_AD_B2C_CLIENT_ID: {{ .Values.azureB2C.clientId | quote }}
  AZURE_AD_B2C_CLIENT_SECRET: {{ .Values.azureB2C.clientSecret | quote }}
{{- end }}
