apiVersion: v1
kind: Secret
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-database
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.auth.database }}"
  POSTGRES_URI: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.auth.database }}"

