{{- if .Values.observability.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-metrics
  labels:
    app: metrics-aggregator
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "carpeta-ciudadana.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
---
# ServiceMonitor for all Carpeta Ciudadana services
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-services
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      {{- include "carpeta-ciudadana.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
---
# PodMonitor for discovering pods
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "carpeta-ciudadana.fullname" . }}-pods
  labels:
    {{- include "carpeta-ciudadana.labels" . | nindent 4 }}
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - gateway
      - citizen
      - ingestion
      - metadata
      - transfer
      - signature
      - mintic-client
      - read-models
      - notification
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}

