/**
 * KEDA (Kubernetes Event-driven Autoscaling) Module
 * 
 * Installs KEDA for event-driven autoscaling based on:
 * - Azure Service Bus queue length
 * - Custom metrics from Prometheus
 * - HTTP traffic
 */

terraform {
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.12"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.24"
    }
  }
}

# Create KEDA namespace
resource "kubernetes_namespace" "keda" {
  metadata {
    name = var.keda_namespace

    labels = {
      name                                 = var.keda_namespace
      "pod-security.kubernetes.io/enforce" = "privileged"
    }
  }
}

# Install KEDA using Helm
resource "helm_release" "keda" {
  name       = "keda"
  repository = "https://kedacore.github.io/charts"
  chart      = "keda"
  version    = "2.12.1"  # Use stable version instead of 2.13.0
  namespace  = kubernetes_namespace.keda.metadata[0].name

  values = [
    yamlencode({
      # Resources for KEDA operator (reduced for Azure for Students)
      resources = {
        operator = {
          limits = {
            cpu    = "500m"
            memory = "512Mi"
          }
          requests = {
            cpu    = "50m"
            memory = "64Mi"
          }
        }
        metricServer = {
          limits = {
            cpu    = "250m"
            memory = "256Mi"
          }
          requests = {
            cpu    = "50m"
            memory = "64Mi"
          }
        }
        webhooks = {
          limits = {
            cpu    = "250m"
            memory = "256Mi"
          }
          requests = {
            cpu    = "50m"
            memory = "64Mi"
          }
        }
      }

      # Replicas (reduced for Azure for Students)
      replicaCount = 1
      
      # Certificates configuration
      certificates = {
        autoGenerated = true
      }

      # Service account
      serviceAccount = {
        create = true
        name   = "keda-operator"
      }
    })
  ]

  depends_on = [
    kubernetes_namespace.keda
  ]
}

# Create TriggerAuthentication for Service Bus (using Azure Workload Identity)
resource "kubernetes_manifest" "servicebus_trigger_auth" {
  count = 0 # Disabled: Apply manually after cluster is ready
  # Original: count = var.enable_servicebus_trigger ? 1 : 0

  manifest = {
    apiVersion = "keda.sh/v1alpha1"
    kind       = "TriggerAuthentication"
    metadata = {
      name      = "azure-servicebus-auth"
      namespace = var.app_namespace
    }
    spec = {
      podIdentity = {
        provider = "azure-workload"
      }
    }
  }

  depends_on = [
    helm_release.keda
  ]
}

# ServiceMonitor for Prometheus (if prometheus-operator is installed)
resource "kubernetes_manifest" "keda_service_monitor" {
  count = 0 # Disabled: Apply manually after cluster is ready
  # Original: count = var.enable_prometheus_monitoring ? 1 : 0

  manifest = {
    apiVersion = "monitoring.coreos.com/v1"
    kind       = "ServiceMonitor"
    metadata = {
      name      = "keda-operator"
      namespace = kubernetes_namespace.keda.metadata[0].name
      labels = {
        app = "keda-operator"
      }
    }
    spec = {
      selector = {
        matchLabels = {
          "app.kubernetes.io/name" = "keda-operator"
        }
      }
      endpoints = [
        {
          port     = "metrics"
          interval = "30s"
        }
      ]
    }
  }

  depends_on = [
    helm_release.keda
  ]
}

