# Loki Configuration for Log Aggregation
# Centralized logging for Carpeta Ciudadana

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Query optimization
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  max_entries_limit_per_query: 5000
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000

# Retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days

# Ingestion rate limits
ingestion_rate_mb: 4
ingestion_burst_size_mb: 6

# Query performance
query_scheduler:
  max_outstanding_requests_per_tenant: 2048

frontend:
  compress_responses: true
  max_outstanding_per_tenant: 2048
  log_queries_longer_than: 5s

# Compactor
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m

