# Promtail Configuration for Log Collection
# Collects logs from Kubernetes pods and ships to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576  # 1MB
    timeout: 10s

scrape_configs:
  # Kubernetes pod logs
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    
    pipeline_stages:
      # Extract log level
      - regex:
          expression: '^.*level=(?P<level>\w+).*$'
      
      # Extract service name from pod
      - labels:
          level:
      
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            message: message
            trace_id: trace_id
            span_id: span_id
            user_id: user_id
            service: service
      
      # Add labels
      - labels:
          service:
          trace_id:
      
      # Drop debug logs in production
      - match:
          selector: '{level="debug"}'
          action: drop
          drop_counter_reason: debug_logs_dropped
    
    relabel_configs:
      # Only collect logs from carpeta-ciudadana namespace
      - source_labels: [__meta_kubernetes_namespace]
        regex: carpeta-ciudadana-.*
        action: keep
      
      # Add namespace label
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      
      # Add pod name
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      
      # Add container name
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      
      # Add service name from pod label
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: service_name
      
      # Add pod IP
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: pod_ip
      
      # Add node name
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
      
      # Set path to pod logs
      - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
        target_label: __path__
        separator: /
        replacement: /var/log/pods/*$1/*.log

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Nginx access logs (if applicable)
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*log
    
    pipeline_stages:
      # Parse nginx access log format
      - regex:
          expression: '^(?P<ip>\S+) - (?P<user>\S+) \[(?P<timestamp>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<bytes>\d+) "(?P<referer>[^"]*)" "(?P<user_agent>[^"]*)"'
      
      - labels:
          method:
          status:
          path:
      
      # Drop health check logs
      - match:
          selector: '{path="/health"}'
          action: drop
          drop_counter_reason: health_check_logs_dropped

