# Development Environment Overrides
# Use with: helm install -f values.yaml -f values-dev.yaml

global:
  environment: development

# CORS - Dev permite todos los orígenes
cors:
  allowedOrigins: "*"
  allowCredentials: false

# MinTIC Hub - Dev permite URLs inseguras para testing
mintic:
  allowInsecureUrls: true

# Ingress for Development
ingress:
  enabled: true
  className: nginx
  tls:
    enabled: false  # Set to true when you have a dev domain
    secretName: carpeta-ciudadana-tls-dev
    certManager:
      enabled: true
      clusterIssuer: letsencrypt-staging  # Use staging for dev
      acmeChallenge: http01
  hosts:
    - host: ""  # Set to dev.carpeta-ciudadana.example.com when available
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: gateway
              port: 8000

# Dev: 1 réplica, sin HPA, recursos mínimos
frontend:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

gateway:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  autoscaling:
    enabled: false

citizen:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

ingestion:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

metadata:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

readModels:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

signature:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"  # Necesita más por operaciones cripto
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  autoscaling:
    enabled: false

transfer:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"  # Saga pattern necesita más
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  autoscaling:
    enabled: false

sharing:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  autoscaling:
    enabled: false

notification:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  autoscaling:
    enabled: false

minticClient:
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  autoscaling:
    enabled: false

