# External Secrets Operator para Azure Key Vault
# Este archivo instala el operador que sincroniza secrets desde Azure Key Vault

apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system

---
# External Secrets Operator Helm Repository
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-repo
  namespace: external-secrets-system
data:
  repo.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-secrets-repo
    type: Opaque
    data:
      url: aHR0cHM6Ly9leHRlcm5hbC1zZWNyZXRzLmNvbW11bml0eS5oZWxtLnNoL2NoYXJ0cw== # https://external-secrets.community.helm.sh/charts

---
# External Secrets Operator Installation
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-install
  namespace: external-secrets-system
data:
  install.sh: |
    #!/bin/bash
    helm repo add external-secrets https://external-secrets.community.helm.sh/charts
    helm repo update
    helm install external-secrets external-secrets/external-secrets \
      -n external-secrets-system \
      --create-namespace \
      --set installCRDs=true
