# Default values for carpeta-ciudadana

global:
  environment: production
  imageRegistry: manuelquistial
  imageTag: latest  # Tag por defecto para todas las imágenes
  imagePullPolicy: Always
  logLevel: INFO
  useWorkloadIdentity: true
  highAvailability: true  # Habilitar alta disponibilidad
  workloadIdentity:
    clientId: ""  # Will be set via Azure Key Vault
    tenantId: ""   # Will be set via Azure Key Vault
  m2mAuth:
    enabled: true

# Azure Key Vault Configuration
keyvault:
  enabled: true
  vaultUrl: ""  # Will be set via Terraform outputs
  clientId: ""  # Will be set via Terraform outputs (External Secrets Managed Identity)

# Migrations configuration
migrations:
  enabled: false  # DISABLED - No migrations should run
  # azureB2C - REMOVED  # Enabled for production
  workloadIdentity:
    clientId: ""  # Will be set via Kubernetes secret
    tenantId: ""   # Will be set via Kubernetes secret
  # Using Azure Key Vault via External Secrets Operator
  m2mAuth:
    enabled: true  # Enabled for inter-service authentication
  resourceOptimization:
    enabled: false  # Enable optimized resource settings
    maxReplicas: 3  # Maximum replicas per service in limited environments
    defaultRequests:
      cpu: "10m"      # Reduced from 25m for limited environments
      memory: "64Mi"   # Reduced from 128Mi for limited environments
    defaultLimits:
      cpu: "100m"     # Reduced from 500m for limited environments
      memory: "256Mi"  # Reduced from 512Mi for limited environments

# Service Bus configuration
serviceBus:
  enabled: true


# CORS Configuration - Permitir dominios generados por Azure
corsOrigins: "http://localhost:3000,http://localhost:8000"  # URLs válidas para desarrollo y producción

# Security Headers - Configurado para HTTP
security:
  hstsEnabled: false  # Disabled for HTTP-only setup
  cspEnabled: false  # Disabled for HTTP-only setup
  cspReportUri: ""  # Optional CSP violation reporting endpoint

# Azure AD B2C configuration - REMOVED

# M2M Authentication (inter-service communication) - Values will be set via Kubernetes secrets
m2mAuth:
  enabled: true
  secretName: m2m-auth
  secretKey: ""  # Will be set via Kubernetes secret
  maxTimestampAge: 300  # 5 minutes
  nonceTtl: 600  # 10 minutes

# Frontend
frontend:
  enabled: true
  replicaCount: 1  # Reducido para ahorrar recursos
  image:
    repository: carpeta-frontend
    tag: latest
  service:
    type: LoadBalancer  # Público - acceso directo
    port: 80
    targetPort: 3000
  resources:
    requests:
      memory: "64Mi"    # Optimized for Next.js production build
      cpu: "10m"        # Optimized for Next.js production build
    limits:
      memory: "128Mi"   # Optimized for Next.js production build
      cpu: "20m"        # Optimized for Next.js production build
  autoscaling:
    enabled: false       # Habilitado para servicios ligeros
    minReplicas: 1
    maxReplicas: 2      # Máximo 2 réplicas para limitaciones de recursos
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 85
  podDisruptionBudget:
    enabled: false
    minAvailable: 1  # Mantener al menos 1 disponible
  # NextAuth configuration - Values will be set via Terraform
  nextAuth:
    secret: "" # Will be set via Kubernetes secret
    url: "" # Will be set via Kubernetes secret
    # Azure AD B2C configuration will be set via Terraform

    metrics:
      - type: Pods
        pods:
          metric:
            name: http_request_duration_seconds_p95
          target:
            type: AverageValue
            averageValue: "500m"  # 500ms p95 latency

# Citizen Service - Moderado uso
citizen:
  enabled: true
  replicaCount: 1  # Reducido para ahorrar recursos
  image:
    repository: carpeta-citizen
    tag: latest
  service:
    type: ClusterIP  # Interno - acceso vía Azure API Management
    port: 8000
  resources:
    requests:
      memory: "128Mi"   # Increased to prevent OOMKilled
      cpu: "10m"        # Increased for stability
    limits:
      memory: "256Mi"   # Increased to prevent OOMKilled
      cpu: "50m"        # Increased for stability
  autoscaling:
    enabled: false       # Habilitado para servicios ligeros
    minReplicas: 1
    maxReplicas: 2      # Máximo 2 réplicas para limitaciones de recursos
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1

# Ingestion Service - Genera SAS URLs, no sube archivos
ingestion:
  enabled: true
  replicaCount: 1  # Reducido para ahorrar recursos
  image:
    repository: carpeta-ingestion
    tag: latest
  service:
    type: ClusterIP  # Interno - acceso vía Azure API Management
    port: 8000
  resources:
    requests:
      memory: "128Mi"   # Increased to prevent OOMKilled
      cpu: "10m"        # Increased for stability
    limits:
      memory: "256Mi"   # Increased to prevent OOMKilled
      cpu: "50m"        # Increased for stability
  autoscaling:
    enabled: false       # Habilitado para servicios ligeros
    minReplicas: 1
    maxReplicas: 2      # Máximo 2 réplicas para limitaciones de recursos
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1

# Signature Service - Alto CPU (criptografía)
signature:
    enabled: true
    replicaCount: 1  # Reducido para ahorrar recursos
    image:
      repository: carpeta-signature
      tag: latest
    service:
      type: ClusterIP  # Interno - acceso vía Azure API Management
      port: 8000
    resources:
      requests:
        memory: "128Mi"   # Optimized for limited environments
        cpu: "50m"        # Optimized for limited environments
      limits:
        memory: "256Mi"   # Optimized for limited environments
        cpu: "100m"       # Optimized for limited environments
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60  # Increased from 20s
      timeoutSeconds: 10        # Increased from 3s
      periodSeconds: 30         # Increased from 10s
      failureThreshold: 3       # Reduced from 3
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 45   # Increased from 15s
      timeoutSeconds: 10        # Increased from 2s
      periodSeconds: 15         # Increased from 5s
      failureThreshold: 3       # Reduced from 2
    autoscaling:
      enabled: false     # Deshabilitado para servicios críticos
      minReplicas: 1
      maxReplicas: 1     # Fijo en 1 réplica para servicios críticos
      targetCPUUtilizationPercentage: 70
    podDisruptionBudget:
      minAvailable: 1


# Transfer Service - Saga pattern, transaccional
transfer:
  enabled: true
  replicaCount: 1  # Reducido para ahorrar recursos
  image:
    repository: carpeta-transfer
    tag: latest
  service:
    type: ClusterIP  # Interno - acceso vía Azure API Management (cambiar de LoadBalancer)
    port: 8000
  resources:
    requests:
      memory: "256Mi"   # Increased for Python + SQLAlchemy
      cpu: "50m"        # Increased for stability
    limits:
      memory: "512Mi"   # Increased for Python + SQLAlchemy
      cpu: "200m"       # Increased for stability
  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 60  # Increased from 20s
    timeoutSeconds: 10       # Increased from 3s
    periodSeconds: 30        # Increased from 10s
    failureThreshold: 3      # Reduced from 3
  readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 45   # Increased from 15s
    timeoutSeconds: 10        # Increased from 2s
    periodSeconds: 15         # Increased from 5s
    failureThreshold: 3       # Reduced from 2
  autoscaling:
    enabled: false     # Deshabilitado para servicios críticos
    minReplicas: 1
    maxReplicas: 1     # Fijo en 1 réplica para servicios críticos
    targetCPUUtilizationPercentage: 70
  podDisruptionBudget:
    minAvailable: 1  # Critical for saga orchestration


# Notification Service - DISABLED - not required by reference document
# notification:
#   enabled: false

# MinTIC Client Service - Rate limiter + Hub calls
minticClient:
  enabled: true
  replicaCount: 1  # Reducido para ahorrar recursos
  image:
    repository: carpeta-mintic_client
    tag: latest
  service:
    type: ClusterIP  # Interno - llamado por otros servicios
    port: 8000
  resources:
    requests:
      memory: "256Mi"  # Increased for Python + SQLAlchemy
      cpu: "50m"        # Increased for stability
    limits:
      memory: "512Mi"   # Increased for Python + SQLAlchemy
      cpu: "200m"        # Increased for stability
  autoscaling:
    enabled: false      # Habilitado para servicios ligeros
    minReplicas: 1
    maxReplicas: 2     # Máximo 2 réplicas para limitaciones de recursos
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1

# Read Models Service (CQRS) - Consumidor de eventos
readModels:
  enabled: false
  replicaCount: 1
  image:
    repository: carpeta-read_models
    tag: latest
  service:
    type: ClusterIP  # Interno - acceso vía Azure API Management
    port: 8007
  resources:
    requests:
      memory: "32Mi"   # Further reduced for limited environments
      cpu: "5m"        # Further reduced for limited environments
    limits:
      memory: "64Mi"   # Further reduced for limited environments
      cpu: "10m"       # Further reduced for limited environments
  autoscaling:
    enabled: false      # Habilitado para servicios ligeros
    minReplicas: 1
    maxReplicas: 2     # Máximo 2 réplicas para limitaciones de recursos
    targetCPUUtilizationPercentage: 80
  podDisruptionBudget:
    minAvailable: 1

# Auth Service - OIDC Provider + Azure AD B2C
auth:
  enabled: true
  replicaCount: 1
  image:
    repository: carpeta-auth
    tag: latest
  service:
    type: ClusterIP  # Interno - acceso vía Azure API Management
    port: 8000
  resources:
    requests:
      memory: "128Mi"   # Optimized for limited environments
      cpu: "50m"        # Optimized for limited environments
    limits:
      memory: "256Mi"   # Optimized for limited environments
      cpu: "100m"       # Optimized for limited environments
  livenessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 60  # Increased from 15s
    timeoutSeconds: 10        # Increased from 3s
    periodSeconds: 30         # Increased from 10s
    failureThreshold: 3       # Reduced from 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 8000
    initialDelaySeconds: 45   # Increased from 10s
    timeoutSeconds: 10        # Increased from 2s
    periodSeconds: 15         # Increased from 5s
    failureThreshold: 3       # Reduced from 5
  autoscaling:
    enabled: false     # Deshabilitado para servicios críticos
    minReplicas: 1
    maxReplicas: 1     # Fijo en 1 réplica para servicios críticos
    targetCPUUtilizationPercentage: 70

# Transfer Worker - Dedicated consumer for transfers (KEDA auto-scaling)
transferWorker:
  enabled: true  # Enabled now that KEDA is installed
  replicaCount: 0  # KEDA controls replicas (scales from 0)
  image:
    repository: carpeta-transfer-worker
    tag: latest
  service:
    type: ClusterIP  # Interno - solo métricas
    port: 8012
  
  # Worker configuration
  queueName: "transfers"
  maxConcurrent: 10  # Max concurrent messages per pod
  prefetchCount: 20  # Prefetch messages for performance
  maxWaitTime: 60    # Max seconds to wait for messages
  
  # Resources (ultra-optimized for limited environments)
  resources:
    requests:
      memory: "128Mi"  # Ultra-optimized for limited environments
      cpu: "10m"       # Ultra-optimized for limited environments
    limits:
      memory: "256Mi"  # Keep limit to prevent OOM
      cpu: "25m"       # Keep CPU for message processing
  
  # KEDA auto-scaling configuration
  keda:
    enabled: false  # Disabled for Azure for Students
    pollingInterval: 30  # Check queue every 30 seconds
    cooldownPeriod: 300   # Wait 5 minutes before scaling down
    minReplicas: 0        # Scale to zero when queue is empty
    maxReplicas: 30       # Maximum replicas under load
    fallbackReplicas: 3   # Fallback if metrics unavailable
    scaleDownStabilization: 300  # Wait 5 min before scale down
    
    # Queue metrics
    queueName: "transfers"
    targetQueueLength: 5  # Target 5 messages per pod
    activationThreshold: 1  # Activate from 0 when 1+ messages
    triggerAuthName: "azure-servicebus-auth"
    
    # Additional triggers (optional)
    cpuTrigger:
      enabled: false
      targetUtilization: 70
    memoryTrigger:
      enabled: false
      targetUtilization: 80
  
  # Node selector for spot instances
  nodeSelector:
    workload: "workers"
    kubernetes.azure.com/scalesetpriority: "spot"
  
  # Tolerations for spot instances
  tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"
  
  # Anti-affinity (spread across nodes)
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - transfer-worker
          topologyKey: kubernetes.io/hostname

  
  # Autoscaling configuration
  autoscaling:
    enabled: false     # Deshabilitado temporalmente por problemas de métricas
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

# PostgreSQL Configuration (Azure Database for PostgreSQL) - Values will be set via Kubernetes secrets
database:
  connectionString: "" # Will be set via Kubernetes secret
  host: "" # Will be set via Kubernetes secret
  port: 5432
  username: "" # Will be set via Kubernetes secret
  password: "" # Will be set via Kubernetes secret
  database: "carpeta_ciudadana"

postgresql:
  enabled: true
  host: "" # Will be set via Kubernetes secret
  port: 5432
  auth:
    username: "" # Will be set via Kubernetes secret
    password: "" # Will be set via Kubernetes secret
    database: carpeta_ciudadana

# Redis Configuration - Values will be set via Kubernetes secrets
redis:
  host: "" # Will be set via Kubernetes secret
  port: 6379
  password: "" # Will be set via Kubernetes secret
  ssl: false

# Azure Storage Configuration - Values will be set via Kubernetes secrets
azure:
  storage:
    accountName: "" # Will be set via Kubernetes secret
    accountKey: "" # Will be set via Kubernetes secret
    containerName: "documents"
    sasTtlMinutes: 15

# Circuit Breaker Configuration
circuitBreaker:
  window: "60s"
  threshold: 5
  cooldown: "120s"

# Service Bus Configuration - REMOVED

# Observability Configuration
observability:
  enabled: false  # Disabled for Azure for Students
  otel:
    endpoint: "http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
  # prometheus: # Removed - using Azure Monitor instead
    enabled: false  # Disabled for Azure for Students
    scrapeInterval: 30s

# CORS Configuration
cors:
  allowedOrigins: "*"  # Overridden in values-dev.yaml and values-prod.yaml
  allowCredentials: false


# Configuration
mintic:
  hubUrl: "" # Will be set via Kubernetes secret
  allowInsecureUrls: false
  rateLimit: 10
  operatorId: "" # Will be set via Kubernetes secret
  operatorName: "" # Will be set via Kubernetes secret



# Service Account (for Workload Identity)
serviceAccount:
  create: true
  annotations: {}
  name: carpeta-ciudadana-sa

# Network Policies (Zero-Trust Networking)
networkPolicies:
  enabled: true  # Set to true to enable (requires NetworkPolicy support in AKS)
  denyAllByDefault: true  # Deny all traffic by default, allow only specific
  allowDNS: true  # Always allow DNS resolution
  allowObservability: true  # Allow Azure Monitor scraping

# Pod Disruption Budgets (High Availability)
podDisruptionBudget:
  enabled: false  # Disabled temporarily to fix template issues
  # Global defaults (can be overridden per service)
  defaultMinAvailable: 1  # At least 1 pod must be available during disruptions


# Ingress - Configurado para usar dominios generados por Azure
ingress:
  enabled: true
  className: nginx  # Use 'nginx' for cert-manager
  annotations:
    # Azure Load Balancer annotations
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-carpeta-ciudadana"
    
    # Nginx Ingress Controller annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disabled for HTTP-only setup
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "1m"
    
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    
    # Timeouts
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
  
  # Rate limiting
  rateLimitRps: 100  # Requests per second per IP
  
  tls:
    enabled: false  # Disabled for HTTP-only setup with Azure-generated domains
    secretName: carpeta-ciudadana-tls
    certManager:
      enabled: false  # Disabled for HTTP-only setup
      
  hosts:
    # Usar dominio generado por Azure Load Balancer
    # El dominio se obtendrá automáticamente del LoadBalancer IP
    - host: ""  # Dejar vacío para usar LoadBalancer IP
      paths:
        # API routing through internal gateway
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: gateway
              port: 8000
        # Frontend (public) - Serves static assets and UI
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port: 80

# OpenTelemetry Collector
otel:
  enabled: false
  replicaCount: 1
  resources:
    requests:
      memory: "64Mi"    # Ultra-optimized for limited environments
      cpu: "10m"        # Ultra-optimized for limited environments
    limits:
      memory: "128Mi"   # Ultra-optimized for limited environments
      cpu: "25m"        # Keep CPU for stability

