# Development Environment Values
# Override default values.yaml for local development

global:
  environment: development
  imageRegistry: manuelquistial
  imagePullPolicy: IfNotPresent
  logLevel: DEBUG  # More verbose logging for development
  useWorkloadIdentity: false  # Disabled for local development

# Migrations configuration for development
migrations:
  enabled: false  # Disabled for local development
  # azureB2C - REMOVED

# Azure B2C configuration - REMOVED

# Service Bus configuration - REMOVED

# M2M Authentication for development
m2mAuth:
  enabled: false  # Disabled for local development

# CORS Configuration (permissive for development)
corsOrigins: "http://localhost:3000,http://localhost:3001,http://localhost:8000"

# Security Headers (relaxed for development)
security:
  hstsEnabled: false  # Disabled for local HTTP
  cspEnabled: false  # Disabled for development flexibility

# Frontend configuration for development
frontend:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    NODE_ENV: "development"
    NEXT_PUBLIC_API_URL: "http://localhost:8000"
    NEXTAUTH_URL: "http://localhost:3000"
    NEXTAUTH_SECRET: "dev-secret-key-for-local-development-only"

# Gateway configuration for development
gateway:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    ENVIRONMENT: "development"
    LOG_LEVEL: "DEBUG"
    CORS_ORIGINS: "http://localhost:3000,http://localhost:8000"

# Database configuration for development
database:
  host: "localhost"
  port: 5432
  name: "carpeta_ciudadana"
  user: "postgres"
  password: "postgres"

# Redis configuration for development
redis:
  host: "localhost"
  port: 6379
  password: ""

# Service URLs for development (local services)
services:
  citizen:
    url: "http://localhost:8001"
  ingestion:
    url: "http://localhost:8002"
  metadata:
    url: "http://localhost:8003"
  transfer:
    url: "http://localhost:8004"
  mintic_client:
    url: "http://localhost:8005"
  signature:
    url: "http://localhost:8006"
  notification:
    url: "http://localhost:8008"

# Ingress configuration for development
ingress:
  enabled: false  # Disabled for local development
  annotations: {}
  hosts: []
  tls: []

# Certificate configuration for development
certificates:
  enabled: false  # Disabled for local development

# Network Policies (Zero-Trust Networking) - Disabled for development
networkPolicies:
  enabled: false  # Disabled for local development flexibility
  denyAllByDefault: false  # More permissive for development
  allowDNS: true
  allowObservability: false  # Not needed for local development