name: E2E Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: tests/e2e/package-lock.json
      
      - name: Install dependencies
        working-directory: tests/e2e
        run: npm ci
      
      - name: Install Playwright Browsers
        working-directory: tests/e2e
        run: npx playwright install --with-deps ${{ matrix.browser }}
      
      - name: Start services (Docker Compose)
        run: |
          docker compose up -d
          sleep 30  # Wait for services to be ready
      
      - name: Wait for frontend
        run: |
          npx wait-on http://localhost:3000 --timeout 120000
      
      - name: Run Playwright tests
        working-directory: tests/e2e
        run: npx playwright test --project=${{ matrix.browser }}
        env:
          BASE_URL: http://localhost:3000
          API_URL: http://localhost:8000
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results-${{ matrix.browser }}
          path: tests/e2e/test-results/
          retention-days: 7
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: tests/e2e/playwright-report/
          retention-days: 7
      
      - name: Stop services
        if: always()
        run: docker compose down

  e2e-smoke:
    name: E2E Smoke Tests (Fast)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        working-directory: tests/e2e
        run: npm ci
      
      - name: Install Playwright
        working-directory: tests/e2e
        run: npx playwright install --with-deps chromium
      
      - name: Start services
        run: |
          # Start infrastructure + application services
          docker compose --profile app up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to be ready..."
          sleep 10
          
          # Check if frontend is accessible
          timeout 120 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 2; done' || {
            echo "Frontend not ready after 2 minutes"
            docker compose ps
            docker compose logs frontend
            exit 1
          }
          
          echo "✅ Services are ready"
      
      - name: Run smoke tests
        working-directory: tests/e2e
        run: npx playwright test auth-flow.spec.ts --project=chromium
      
      - name: Stop services
        if: always()
        run: docker compose down

