name: Run Tests

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - citizen
          - ingestion
          - metadata
          - transfer
          - signature
          - sharing
          - auth
          - gateway
          - mintic_client
          - notification
          - read_models
          - transfer_worker
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: |
          poetry install --with dev --no-root
      
      - name: Run pytest
        working-directory: services/${{ matrix.service }}
        run: |
          poetry run pytest tests/ \
            --cov=app \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=70 \
            -v
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: services/${{ matrix.service }}/coverage.xml
          flags: ${{ matrix.service }}
          name: ${{ matrix.service }}-coverage

  common-tests:
    name: Common Package Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        working-directory: services/common
        run: |
          poetry install --with dev --no-root
      
      - name: Run pytest
        working-directory: services/common
        run: |
          poetry run pytest carpeta_common/tests/ \
            --cov=carpeta_common \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=80 \
            -v
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: services/common/coverage.xml
          flags: common
          name: common-coverage

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, common-tests]
    if: always()
    
    steps:
      - name: Check test results
        run: |
          echo "✅ All tests completed"
          echo "Check individual job results above"

